service: sls-apig-domain-users

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, env:SLS_STAGE, 'dev'}
  region: ${opt:region, env:SLS_REGION, 'us-east-1'}
  stackName: ${self:provider.stage}-${self:service}
  disableRollback: true
  apiName: ${self:provider.stackName}
  profile: ${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}
  memorySize: 128
  timeout: 10
  logRetentionInDays: 14
  deploymentBucket:
    name: ${self:provider.region}-${self:service}-deploys
    serverSideEncryption: AES256
  apiGateway:
    restApiId:
      Fn::ImportValue: ${self:provider.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      Fn::ImportValue: ${self:provider.stage}-ApiGatwayRestApiRootResourceId
  environment:
    tableName: ${file(../database/serverless.yml):custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::ImportValue: ${self:provider.stage}-ResourcesTableArn

functions:
  get:
    handler: handler.main
    events:
      - http: GET users
        cors: true
        authorizer: aws_iam

resources:
  Resources:
    ResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: resourceId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: resourceId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

plugins:
  # https://github.com/MikeSouza/serverless-deployment-bucket
  - serverless-deployment-bucket
  # https://github.com/dherault/serverless-offline
  - serverless-offline
  # https://github.com/dougmoscrop/serverless-plugin-common-excludes
  - serverless-plugin-common-excludes
  # https://github.com/yonomi/serverless-plugin-encode-env-var-objects
  - serverless-plugin-encode-env-var-objects
  # https://github.com/svdgraaf/serverless-pseudo-parameters
  - serverless-pseudo-parameters
